title: Joel's Page
author: thelarkscend1ng
email: joelhansenlol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is gonna be the spot.

# social links
twitter_username: notwitter # DO NOT include the @ character, or else the build will fail!
github_username:  thelarkascend1ng # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
